# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5H2BGz-q0DpT_-HYknkFYf-dmUyu3au
"""

import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5,8,7,9]
y = [2, 3, 5, 7, 11,4,98,1]

#1.Line plot
print("Line Plot")
plt.plot(x,y)
plt.show()

#2.Scatter Plot
print("Scatter Plot")
plt.scatter(x,y)
plt.show()

#3.Bar Plot
print("Bar Plot")
plt.bar(x,y)
plt.show()

#4.Histogram
print("Histogram")
data = [1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,6]
plt.hist(data)
plt.show()

#5.Pie Chart
print("Pie Chart")
labels = ['A','B','C','D']
sizes = [15,30,45,10]
plt.pie(sizes,labels=labels)
plt.show()

plt.title('Simple Line Plot')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

plt.show()