# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5H2BGz-q0DpT_-HYknkFYf-dmUyu3au
"""

import pandas as pd
import matplotlib.pyplot as plt
data = {
    'Year': [2010,2015,2020,2025,2030],
    'Sales': [253,412,658,100,365]

}
df = pd.DataFrame(data)
df.plot(x = 'Year', y = 'Sales', kind = 'line')

plt.title('Sales Over Years')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.show()