# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U20R2NrwMC9nLDNPd1vZak_YogIjlBUO
"""

import seaborn as sns
import matplotlib as plt
import numpy as np

tips = sns.load_dataset('tips')
#sns.scatterplot(x = "total_bill",y = "tip", data = tips)
#plt.show()

#sns.lineplot(x = "total_bill",y = "tip", data = tips)
#plt.show()

#sns.histplot(tips["total_bill"])
#plt.show()

#sns.boxplot(x="day",y="total_bill",data=tips)
#plt.show()

#data = np.random.rand(11,13)
#sns.heatmap(data)
#plt.show()

#.pairplot(tips)
#plt.show()

g = sns.FacetGrid(tips, col="time")
g.map(sns.histplot, "total_bill")
plt.show()